---
title: "Lab 01 - Hello R"
author: "Yuxin Xie"
date: "1/22/2025"
output: 
  html_document: 
    fig_height: 4
    fig_width: 9
---

## Load packages and data

install.packages("tidyverse")
install.packages("datasauRus")

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```

## Exercises

### Exercise 1 
?datasaurus_dozen
nrow(datasaurus_dozen)
ncol(datasaurus_dozen)
# based on the help file, there are 1846 rows and 3 columns in the datasaurus_dozen file. 
# the 3 variables are: dataset, x, y 

datasaurus_dozen %>%
  count(dataset) %>%
  print()


### Exercise 2 

dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()

dino_data %>%
  summarize(r = cor(x, y))
# r = -0.0645, which is close to 0. there is no linear relationship between x and y. 


### Exercise 3

star_data <- datasaurus_dozen %>%
  filter(dataset == "star")

ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()

star_data %>%
  summarize(r = cor(x, y))
# r of the star dataset is -0.0630, |r| is smaller than the r of dino. but still close to 0, no linear relationship between x and y in star dataset


### Exercise 4
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()

circle_data %>%
  summarize(r = cor(x, y))
# r of the star dataset is -0.0683, |r| is larger than the r of dino. but still close to 0, no linear relationship between x and y in circle dataset



### Exercise 5

This is your final exercise! Add code and narrative as needed. Be creative and show off what you’ve learned so far.
Add code and narrative as needed.

To add additional R chunks, you can either type the backticks, curly braces, and the letter `r`, or use the "Insert Chunk" button above (the green C+ icon). Have fun!


